_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

strategy: ddp

min_epochs: 1000
max_epochs: 5000

accelerator: gpu
devices: 1

# mixed precision for extra speed-up
# precision: 16

# perform a validation loop every N training epochs
check_val_every_n_epoch: 50

# log metrics every N steps
log_every_n_steps: 100

# add gradient clipping to prevent exploding gradients
gradient_clip_val: 10.0
gradient_clip_algorithm: norm

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
