encoder:
  _target_: src.vae_module.positional_embeddings.SinusoidalPositionalEmbedding
  max_len: ${vae_module.max_atoms}
decoder:
  _target_: src.vae_module.positional_embeddings.SinusoidalPositionalEmbedding
  max_len: ${vae_module.max_atoms}
