defaults:
  - encoder: transformer
  - decoder: transformer
  - pos_embedding: sinusoidal

_target_: src.vae_module.vae_module.VAEModule

latent_dim: 8

loss_weights:
  atom_types: 1.0
  lengths: 1.0
  angles: 10.0
  frac_coords: 10.0
  kl: 1e-5
  fa: 0.0

augmentation:
  translate: true # translate cartesian and fractional coordinates
  rotate: true # rotate lattice and cartesian coordinates

noise:
  ratio: 0.0 # ratio of noise to apply to the input data
  corruption_scale: 0.1 # Ã…

atom_type_predict: True

structure_matcher:
  _target_: pymatgen.analysis.structure_matcher.StructureMatcher
  ltol: 0.3
  stol: 0.5
  angle_tol: 10

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0

scheduler: ${scheduler}

max_atoms: 100

index_embedding:
  encoder:
    _target_: src.vae_module.positional_embeddings.SinusoidalPositionalEmbedding
    max_len: ${vae_module.max_atoms}
  decoder:
    _target_: src.vae_module.positional_embeddings.SinusoidalPositionalEmbedding
    max_len: ${vae_module.max_atoms}
