# @package _global_
# RL Custom Reward Experiment Configuration
#
# Example: Atomic density reward using CustomReward component
# See user guide: docs/user-guide/rewards/atomic-density.md

data:
  data_dir: ${paths.data_dir}/mp-20
  batch_size: 5

trainer:
  max_steps: 200

rl_module:
  ldm_ckpt_path: ${hub:mp_20_ldm_base}
  vae_ckpt_path: ${hub:mp_20_vae}

  rl_configs:
    num_group_samples: 64
    group_reward_norm: true

  reward_fn:
    normalize_fn: std
    components:
      - _target_: custom_reward.atomic_density.AtomicDensityReward

logger:
  wandb:
    name: rl_atomic_density
